### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by lostmygithubaccount** [drabastomek/dask-cloudprovider#42]
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
<ipython-input-8-d6986c496393> in <module>
----> 1 cluster = AzureMLCluster(ws, ct, env, jupyter=True, asynchronous=False, datastores=[ws.datastores[datastore] for datastore in ws.datastores])

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dask_cloudprovider/providers/azure/azureml.py in __init__(self, workspace, compute_target, environment_definition, experiment_name, initial_node_count, use_gpu, n_gpus_per_node, jupyter, jupyter_port, dashboard_port, scheduler_port, admin_username, admin_ssh_key, datastores, code_store, asynchronous, **kwargs)
    207             self._loop_runner.start()
    208             self.sync(self.get_defaults)
--> 209             self.sync(self.create_cluster)
    210 
    211     async def get_defaults(self):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    160             return future
    161         else:
--> 162             return sync(self.loop, func, *args, **kwargs)
    163 
    164     async def _logs(self, scheduler=True, workers=True):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    331     if error[0]:
    332         typ, exc, tb = error[0]
--> 333         raise exc.with_traceback(tb)
    334     else:
    335         return result[0]

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/utils.py in f()
    315             if callback_timeout is not None:
    316                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 317             result[0] = yield future
    318         except Exception as exc:
    319             error[0] = sys.exc_info()

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dask_cloudprovider/providers/azure/azureml.py in create_cluster(self)
    357         while(self.same_vnet is None):
    358             try:
--> 359                 await self.sync(self.__check_if_scheduler_ip_reachable)
    360             except socket.timeout:
    361                 time.sleep(1)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/dask_cloudprovider/providers/azure/azureml.py in __check_if_scheduler_ip_reachable(self)
    295         try:
    296             ip, port = self.scheduler_ip_port.split(':')
--> 297             socket.create_connection((ip, port), 5)
    298             self.same_vnet = True
    299             self.__print_message('On the same VNET')

/anaconda/envs/azureml_py36/lib/python3.6/socket.py in create_connection(address, timeout, source_address)
    722 
    723     if err is not None:
--> 724         raise err
    725     else:
    726         raise error("getaddrinfo returns an empty list")

/anaconda/envs/azureml_py36/lib/python3.6/socket.py in create_connection(address, timeout, source_address)
    711             if source_address:
    712                 sock.bind(source_address)
--> 713             sock.connect(sa)
    714             # Break explicitly a reference cycle
    715             err = None

ConnectionRefusedError: [Errno 111] Connection refused

**Comment by lostmygithubaccount** [comment]
Compute instance - not on VNET
Compute target - also not on VNET

**Comment by drabastomek** [comment]
@lostmygithubaccount Can you confirm if this is still happening? I could not repro this.
