### ISSUE TITLE
import error caused by PeriodicCallback

### ISSUE THREAD

**Issue by alexdeng** [drabastomek/dask-cloudprovider#96]
This line gives import error. It seems PeriodicCallback no longer exists in distributed.utils 
from distributed.utils import (
    LoopRunner,
    PeriodicCallback,
    log_errors,
    ignoring,
    format_bytes,
)

**Comment by alexdeng** [comment]
distributed version 2.16.0

**Comment by drabastomek** [comment]
Closed via #100
